### PR TITLE
Upgrades scrum2b to work with Rails 5.0 & Redmine 4.x

### PR DESCRIPTION
**Pull request by klhurley**

### CODE REVIEW

**Comment by valentinzaracho** [comment]
Gooo to REDMINE 4

**Comment by klhurley** [comment]
> @klhurley Is there any git clone link for this upgrade??

git clone https://github.com/klhurley/scrum2b.git

**Comment by VGIT-VHL** [comment]
I have a problem when creating and updating an issue. Is it possible to fix?

####  Logs:  ####
**when Create**:
app/models/issue.rb:434:in `assign_attributes'
app/models/issue.rb:200:in `initialize'
plugins/scrum2b/app/controllers/s2b_boards_controller.rb:146:in `create'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Started POST "/redmine/s2b_boards/create" for 10.111.110.4 at 2020-01-05 09:36:59 +0000
Processing by S2bBoardsController#create as JSON
  Parameters: {"project_id"=>"1", "issue"=>{"project_id"=>"1", "author_id"=>"1", "subject"=>"test issue", "description"=>"test", "tracker_id"=>"1", "assigned_to_id"=>"1", "priority_id"=>"2"}}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 8ms (ActiveRecord: 1.9ms)

NoMethodError (undefined method `stringify_keys!' for #<ActionController::Parameters:0x00007f7cac907e70>
Did you mean?  stringify_keys):


**when Update**:
app/models/issue.rb:434:in `assign_attributes'
plugins/scrum2b/app/controllers/s2b_boards_controller.rb:124:in `update'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Started POST "/redmine/s2b_boards/update" for 10.111.110.4 at 2020-01-05 09:05:56 +0000
Processing by S2bBoardsController#update as JSON
  Parameters: {"issue"=>{"id"=>"1", "project_id"=>"1", "author_id"=>"1", "subject"=>"New issue", "description"=>"Test\r\ntest1\r\n", "tracker_id"=>"1", "assigned_to_id"=>"1", "priority_id"=>"2"}, "project_id"=>"1"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 8ms (ActiveRecord: 1.9ms)

NoMethodError (undefined method `stringify_keys!' for #<ActionController::Parameters:0x00007f7cacec6b90>
Did you mean?  stringify_keys):

### Server Configuration ###:
Environment:
  Redmine version                4.0.6.stable.19406
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.7
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  redhopper                      2.0.0
  redmine_helpdesk               0.0.17
  scrum2b                        2.0

**Comment by klhurley** [comment]
Fixed issue with creating an issue inside the Scrum2B component.
